export { default as sharedProto } from './datas/shared_proto.json'
export { default as resumeProto } from './datas/resume_proto.json'
export * from './@types/entity'
export * from './db'
export * from './repository'